### ISSUE TITLE
Not working when built for production 

### ISSUE THREAD

**Issue by jwoodmansey** [knapcio/react-leaflet-pixi-overlay#1]
Hi,

I can't get this plugin to work when built for production. 

It works perfectly locally running on a dev server but when built for production using react-scripts 'build' nothing is rendered. I've done quite a lot of digging through the source of this but cannot seem to work out what could be wrong.

Any pointers would be much appreciated.

Thanks

**Comment by knapcio** [comment]
Hi @jwoodmansey 
Sorry for the late reply. Could you please provide your webpack/babel config and package.json?

**Comment by ajshukury** [comment]
I can't run it in IE. Here is my .bablrc:
`{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    "@babel/plugin-proposal-class-properties" ,
    "@babel/plugin-syntax-dynamic-import"
  ]
}`

webpack
`        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: "babel-loader"
                }
            },
            {
                test: /\.(png|woff|woff2|eot|ttf|svg)$/,
                loader: "url-loader?limit=100000"
            },
            {
                test: /\.css$/,
                use: "css-loader/locals"
            }
        ]`

and part of the pckages.json
`"devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/preset-env": "^7.9.0",
    "@babel/preset-react": "^7.9.4",
    "@date-io/moment": "^1.3.13",
    "@material-ui/core": "^4.9.10",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.49",
    "@material-ui/pickers": "^3.2.10",
    "@material-ui/styles": "^4.9.10",
    "ag-grid-community": "^20.2.0",
    "ag-grid-enterprise": "^20.2.0",
    "ag-grid-react": "^20.2.0",
    "babel-loader": "^8.1.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "bitbar-webpack-progress-plugin": "^1.0.0",
    "clsx": "^1.1.0",
    "convert-units": "^2.3.4",
    "copy-webpack-plugin": "^4.6.0",
    "css-loader": "^1.0.1",
    "es6": "0.0.7",
    "es6-object-assign": "^1.1.0",
    "es6-promise": "^4.2.8",
    "fs": "0.0.1-security",
    "gulp": "^4.0.0",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "isomorphic-fetch": "^2.2.1",
    "js-file-download": "^0.4.10",`

**Comment by ajshukury** [comment]
@knapcio  any thoughts?

**Comment by frontcraft** [comment]
Indeed, this package breaks the webpack build when you use code minification. The error is not so descriptive:
`ERROR in unknown: Unexpected token (82915:66)`

...but it occurs only when you use the Babel Minify Webpack Plugin https://github.com/webpack-contrib/babel-minify-webpack-plugin .

**Comment by frontcraft** [comment]
I figured out that it is not the react-leaflet-pixi-overlay itself that causes the error on compilation. It is about dependencies. Updating leaflet-pixi-overlay and pixi.js packages to the latest version solves the problem.

**Comment by hugobarragon** [comment]
> I figured out that it is not the react-leaflet-pixi-overlay itself that causes the error on compilation. It is about dependencies. Updating leaflet-pixi-overlay and pixi.js packages to the latest version solves the problem.

what version and what packages did you had to update to fix this issue?

**Comment by hugobarragon** [comment]
@frontcraft if possible write the versions here for us to update on the package dependencies, so we can close this issue

**Comment by knapcio** [comment]
Fixed in 1.0.9 :)
