### ISSUE TITLE
_reactLeaflet.useLeaflet is not a function - Is react-leaflet-pixi-overlay compatible with react-leaflet 3.x ?

### ISSUE THREAD

**Issue by HarborneD** [knapcio/react-leaflet-pixi-overlay#10]
I'm getting `_reactLeaflet.useLeaflet is not a function ` when using `<PixiOverlay markers={markers} />`

I notice that the example uses <Map> rather than <MapContainer> so I am assuming the error I'm seeing is a react-leaflet 2.x vs 3.x issue but I've also seen some comments from people using this library with 3.x (apparently? ) 

Many thanks!

**Comment by adefrutoscasado** [comment]
I have the same problem:
https://codesandbox.io/s/trusting-newton-8el09

**Comment by hugobarragon** [comment]
No react-lefaletv3 is not suported yet but it will be

**Comment by oyhan** [comment]
> No react-lefaletv3 is not suported yet but it will be

It's getting late

**Comment by hugobarragon** [comment]
Fell free to open a PR 😃

**Comment by victorlin** [comment]
This comes from the dependency `use-leaflet`. I've opened an issue there vadzim/use-leaflet#109 but last activity on the repo was ~1 year ago 😕

**Comment by vadzim** [comment]
Oh, guys... I didn't actually notice someone uses my module... Thanks, gonna fix it :)

**Comment by hugobarragon** [comment]
Hi, yes it cames from use-leaflet, but react-leaflet has a internal hook on v3 so it does not make sense to keep using another lib, for now, react-leaflet-pixi-overlay works great and it was designed on react-leaflet v2, i will try this week to open a PR for v3  support guys

**Comment by danh00** [comment]
any update on this? would be very handy to have, otherwise I might try to figure it out

**Comment by hugobarragon** [comment]
this PR removes use-leaflet lib to reduce deps and now will rework no react leaflet v3
https://github.com/knapcio/react-leaflet-pixi-overlay/pull/17

**Comment by hugobarragon** [comment]
React leaflet v3 updated!!  
https://github.com/knapcio/react-leaflet-pixi-overlay/pull/18

**Comment by danh00** [comment]
thanks so much for opening that PR!

I'm giving it a go now and I'm finding the markers are not showing up . I can still click it and it's functioning normally just that the marker is not visible. Any ideas?

**Comment by danh00** [comment]
thanks for this hugo!

**Comment by danh00** [comment]
could you give an example of how to use onClick in the marker to open the popup?

**Comment by hugobarragon** [comment]
> could you give an example of how to use onClick in the marker to open the popup?

hi, please try the readme docs, if it does not work, open a new issue please

**Comment by knapcio** [comment]
As far as I know @hugobarragon's PRs resolved the issue. Closing :)
