### ISSUE TITLE
Feature: support for custom icons

### ISSUE THREAD

**Issue by virtumonde** [knapcio/react-leaflet-pixi-overlay#2]

**Comment by SaniyaFareye** [comment]
Any update for this?

**Comment by knapcio** [comment]
Hi guys, thanks for the request. I just pushed the updated version where you can add custom icons. Please check the updated Readme file for more details.

**Comment by ehortle** [comment]
Love your work, amazing development

**Comment by SaniyaFareye** [comment]
Thank you for the update. And for your info click and mouseover are also not working

**Comment by knapcio** [comment]
@SaniyaFareye thanks for the comment. If you think there's a bug, please open a new issue and provide a sample of your code.
