### ISSUE TITLE
Can i specify svg custom icon saved on disk?

### ISSUE THREAD

**Issue by SonGokussj4** [knapcio/react-leaflet-pixi-overlay#28]
Hi, I'm trying to apply CustomIcon but don't know how.

Instead of `<svg style=...></svg>` I want to use `/images/icons/computer2.svg` which I have in my public folder.

When specifying custom leaflet icon, I can do this with:

```js
const iconComputer = new L.Icon({
    iconUrl: `/images/icons/computer2.svg`,
    iconSize: [20, 20],
    iconAnchor: [10, 20],
  })
```

How can I apply this on pixi overlay?

```js
const markers = [{
  position: [10, 10],
  id: 'someIDUniqueToMarker',
  iconId: 'someIDUniqueToIcon',  // used for cache
  customIcon: '<img src="/images/icons/computer2.svg" alt="My Computer">',
}],
```

**Comment by knapcio** [comment]
Hi, please read the "Custom Icon" section in Readme. Cheers.
