### ISSUE TITLE
Multiple overlays

### ISSUE THREAD

**Issue by jfaraklit** [knapcio/react-leaflet-pixi-overlay#3]
```
    {markersArray.map(markers => (
                       <PixiOverlay markers={markers} />
                ))}
```
Getting 
Error: Cannot add resources while the loader is running.
The ideas is to have a dynamic number of overlays based on your selection on parent component. 
Any thoughts?

**Comment by knapcio** [comment]
Hi @ajshukury 
I haven't used the library this way. Could you please explain what are you trying to achieve by creating multiple overlays? Maybe it would be better to flatten your markers array and then add to a single overlay?

**Comment by ajshukury** [comment]
@knapcio thanks for your comment. The idea for us is to draw a large number of markers reporting weather observation in the roads using some smart sensors attached to tracks. It is basically 200 meters apart for surface observation. There are multiple tracks on different roads and directions and we need to handle and manage each track seperlty. So that we can add some filtering and other stuff.
Think of each track as an overly
Something like this https://deck.gl/#/examples/custom-layers/data-filter but deck.gl is not very good with leaflet and our map is react-leaflet.

**Comment by knapcio** [comment]
@ajshukury sounds interesting!
Wouldn't the below code solve the whole problem though?
```js
<PixiOverlay markers={markers.flat()} />
``` 
Also today I added the functionality allowing custom SVG icons. Please check the updated Readme file.

**Comment by ajshukury** [comment]
@knapcio well the amount of data is massive so circulemarkers do have performance issues when reaching around 80k or more.
<PixiOverlay markers={markersArray.flat()} /> might work but still the amount of data is massive and we want to enable each track individually. 
![image](https://user-images.githubusercontent.com/14077606/85614059-871d1a80-b628-11ea-87d0-055f94dda838.png)

**Comment by hugobarragon** [comment]
> @knapcio well the amount of data is massive so circulemarkers do have performance issues when reaching around 80k or more.
> `<PixiOverlay markers={markersArray.flat()} />` might work but still the amount of data is massive and we want to enable each track individually.
> ![image](https://user-images.githubusercontent.com/14077606/85614059-871d1a80-b628-11ea-87d0-055f94dda838.png)

i will create a code sandbox working example with only one instance of ReactPixiOverlay and notify you here

**Comment by hugobarragon** [comment]
I will make and example with the switch spliting the 80k in two chunks of 40k and updating on switch changes
80k markers example all at same time  

[![Edit react-leaflet-pixi-overlay80k](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-leaflet-pixi-overlay80k-bcm57?fontsize=14&hidenavigation=1&theme=dark)
