### ISSUE TITLE
Custom Icon position issue

### ISSUE THREAD

**Issue by jfaraklit** [knapcio/react-leaflet-pixi-overlay#4]
When using customIcon, the potion is not correct and when you zoom in/out the map the position changes.

When I use a default icon with pixi
![image](https://user-images.githubusercontent.com/14077606/87440946-8a208080-c5c0-11ea-9f81-0a1f48fee907.png)

When I use a custom icon with pixi
![image](https://user-images.githubusercontent.com/14077606/87440989-94db1580-c5c0-11ea-991e-1cb3a0e6654b.png)

But the same lat/long shows here when drawn directly ask leaflet marker not Pixi stuff. 
![image](https://user-images.githubusercontent.com/14077606/87441041-a3c1c800-c5c0-11ea-9530-17f724f14965.png)

The same points are drawn using normal marker and circle. You can see the pixi webgl filled circles are off.
![image](https://user-images.githubusercontent.com/14077606/87706989-6864fc00-c76e-11ea-96fe-439a24374cdb.png)

Any thoughts? is it the offset?

**Comment by ajshukury** [comment]
@knapcio any thoughts?

**Comment by hugobarragon** [comment]
I will investigate this and try to solve this problem so markers icon can be calibrated, maybe with marker.anchor.set
