### ISSUE TITLE
Restrucutre lib, not working with jest and some browsers

### ISSUE THREAD

**Issue by hugobarragon** [knapcio/react-leaflet-pixi-overlay#7]
This lib is not being compiled to es5 when published to npm, some folder restructure should do the work.

not working with aplications with jest, for unit testing and es5 browser and aplications
and has no types

the objective is to not change any funcionality, but fix thsi structural changes, without any breaking change
add prettier and eslint for sync changes to the project and keep same format

**Comment by knapcio** [comment]
It's probably because I always use this lib with ts/babel/webpack packed projects which use polyfills. Do you think we should build some dist to be used as a dependency?

**Comment by hugobarragon** [comment]
yes its just use babel to compile and publish on npm a lib/es folder that is es5 and add typescript for better error handlings and autocomplete and documentacion on compile time...


https://material-ui.com/guides/minimizing-bundle-size/#ecmascript

https://medium.com/@SunnyB/how-to-convert-es6-into-es5-using-babel-1b533d31a169

![image](https://user-images.githubusercontent.com/35630927/107559450-00777680-6bd4-11eb-8097-b9db6c863167.png)

**Comment by knapcio** [comment]
Ok, I think it's done. If you have any comments I'm happy to hear them. Please note that the usage of the library changed from
`import { PixiOverlay } from 'react-leaflet-pixi-overlay';`
to
`import PixiOverlay from 'react-leaflet-pixi-overlay';`

**Comment by hugobarragon** [comment]
i thought if this, and makes sense to be like this ahahahah, i didnt suggested this change so it does not became a breaking change

**Comment by hugobarragon** [comment]
Its already changed no problem, i am testing , and looks good, will just add on readme a version aware, that its not a major but breaks previous import usage
it still needs typescript to fix usage on new versions of react with and without typescript it will work and give, i will open a pr for this in future dont worry, add prettier and eslint to.

![Untitled](https://user-images.githubusercontent.com/35630927/107565006-0886e480-6bdb-11eb-9a2c-0c840501d3fc.png)

![image](https://user-images.githubusercontent.com/35630927/107564914-e4c39e80-6bda-11eb-8e70-a9af182164d5.png)

**Comment by knapcio** [comment]
Great! Feel free to contribute any time as I don't feel like these configurations are my strong side. Thank you!

**Comment by hugobarragon** [comment]
> Great! Feel free to contribute any time as I don't feel like these configurations are my strong side. Thank you!

yeah no problem hehehe
you can give a look at this project for the structure

https://github.com/hugobarragon/leaflet-drift-marker

on npm only has lib, for faster download, that is the es5 compiled to work on 99%
![image](https://user-images.githubusercontent.com/35630927/107565623-c14d2380-6bdb-11eb-9914-04ace8bcfecd.png)

**Comment by hugobarragon** [comment]
when using jest for unit testing, now gives different error, but its better, previously error was that , the lib was not em es5 and not compatible, so we are on good path lets go
